### ISSUE TITLE
Timing issue with initial hide when opening a new ticket.

### ISSUE THREAD

**Issue by clong-** [pchhetri/hide-zdapps-chrome-ext#12]
Occasionally when loading a new ticket, only some apps (or no apps at all) are hidden.

It was working okay when we were polling the URL and app panel population, and now is not with the ember ready check implemented by @pchhetri. That being said, constant polling isn't a great way to handle things. We'll have to weigh it out.

**Comment by clong-** [comment]
Reverted to polling for now (as of PR #14) so we've got a dependable baseline for building out the rest. May revisit the ember check later, so I'll leave this bug open for now.

**Comment by pchhetri** [comment]
Doing some research, I have found 3 ways to go about this:

1. Append a script to the body and then after this script has executed, run the function to hide apps.

```
    var script = document.createElement('script');
    script.type = "text/javascript";
    script.src = chrome.extension.getURL("blankscript.js");
    if (document.body) {
        document.body.appendChild(script);
        script.onload = function() {
            document.body.removeChild(script);
            console.log('All things have loaded...potentially');
            hideApps();

        };
    }
```

Issue with method 1 is that in the users page the script we append to the body executes before the apps panel loads. Same thing occurs if one opens multiple tickets quickly 

2\. We can utilize a listener looking for `domnodeinserted` event, however for best result this would require that we bind to a specific node. And as far as I can discern that can only be done by polling the page essentially, so we are back at square one. However, I think it can be used once the page is initially loaded.

Article on how to use this: http://gabrieleromanato.name/jquery-how-to-use-the-domnodeinserted-event-and-why-its-important/

http://stackoverflow.com/questions/9778962/handler-for-dynamically-created-dom-nodes-as-they-are-inserted

Why its not best practice: http://lists.w3.org/Archives/Public/public-webapps/2011JulSep/0779.html

3\. Use the polling method we have now, sure its not ideal but it gets the job done. One caveat with this is, we have to ensure that it doesn't poll for too long. As an example if we go to the organization through the breadcrumb then the url is still /tickets/{id} but there is no apps sidebar and thus it polls for ever.
